2022-01-21 16:04:38,008 ERROR: Exception on /user/susan [GET] [in E:\Programming\Libraraya\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Programming\Libraraya\app\routes.py", line 78, in user_page
    return render_template('user.html', user=user, posts=posts)
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Programming\Libraraya\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "E:\Programming\Libraraya\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Programming\Libraraya\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Programming\Libraraya\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Programming\Libraraya\app\templates\user.html", line 17, in block 'content'
    <p><a href="{{ url_for('unfollow') }}">Unfollow</a></p>
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "E:\Programming\Libraraya\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "E:\Programming\Libraraya\venv\lib\site-packages\werkzeug\routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unfollow'. Did you forget to specify values ['username']?
